# Generated by Django 4.1 on 2022-09-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0002_taskitem_status_alter_taskitem_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="taskitem", name="status",),
        migrations.AddField(
            model_name="taskitem",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
    ]
